// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbmttapvkjdfevzdprgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtibXR0YXB2a2pkZmV2emRwcmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDI3MzUsImV4cCI6MjA2MTc3ODczNX0.5qaSQgK_9WJnXH0FjsOcuJWEdKlvoJ8cPxDHX4GAFHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);